sudo: required

language: javascript

services:
    - docker

before_install:
    - docker build -t mkenney/npm:latest .
    - cd test

script:
    - docker run --rm -t -i -v $(pwd):/src:rw mkenney/npm:latest /run-as-user /usr/local/bin/node --version
    - docker run --rm -t -i -v $(pwd):/src:rw mkenney/npm:latest /run-as-user /usr/local/bin/npm install
    - docker run --rm -t -i -v $(pwd):/src:rw mkenney/npm:latest /run-as-user /usr/local/bin/bower install
    - docker run --rm -t -i -v $(pwd):/src:rw mkenney/npm:latest /run-as-user /usr/local/bin/grunt
    - docker run --rm -t -i -v $(pwd):/src:rw mkenney/npm:latest /run-as-user /usr/local/bin/gulp
