sudo: required
nguage: javascript

services:
    - docker

before_install:
    - docker build -t camiloruiiz/gulp:latest .

script:
    - docker run -d -v $(pwd):/opt camiloruiiz/gulp:latest

after_success:
    - cd ../ci
    - sh ./deploy.sh
