version: "2"

services:  
  web:
    build: ./
    image: gulp:myapp    
    container_name: gulp-web
    ports: 
      - "3000:3000"
      - "3001:3001"
    command: npm run dev
    volumes:
      - ./app:/app
      - ./ap:/app/modules
