version: "2"

volumes:
  node_modules:
    driver: local

services:  
  web:
    image: camiloruiiz/docker-gulp:latest    
    container_name: gulp-web
    ports: 
      - "3000:3000"
      - "3001:3001"
    volumes:
       - ./:/opt
